### ISSUE TITLE
update to `next: 14.2` 

### ISSUE THREAD

**Issue by prestonbourne** [prestonbourne/www-2024#2]
I unfortunately can't smoothly update to next.js 14.2 because of some error with `next-mdx-remote` fortunately, i literally work at the company that made it so perhaps I can try to take a look into fixing the error.

Here's the build error
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/.pnpm/next-mdx-remote@5.0.0_@types+react@18.2.69_react@18.2.0/node_modules/next-mdx-remote/rsc.js from /vercel/path0/.next/server/app/page.js not supported.
Instead change the require of rsc.js in /vercel/path0/.next/server/app/page.js to a dynamic import() which is available in all CommonJS modules.
    at mod.require (/vercel/path0/node_modules/.pnpm/next@14.2.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at 8549 (/vercel/path0/.next/server/app/page.js:1:824)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:127)
    at 2874 (/vercel/path0/.next/server/chunks/495.js:1:1142)
    at Object.t [as require] (/vercel/path0/.next/server/webpack-runtime.js:1:127) {
  code: 'ERR_REQUIRE_ESM',
  digest: '3199581875'
}
```

And here's a good place to start digging around: https://github.com/hashicorp/next-mdx-remote/issues/381

**Comment by Jervx** [comment]
Hi this is a noob question, just wondering if next-mdx-remote will support client component in future?

```tsx

"use client";
import { Message } from "ai";
import Image from "next/image";
import React, { useCallback, useEffect, useState } from "react";

import { serialize } from "next-mdx-remote/serialize";
import { MDXRemoteSerializeResult, MDXRemote } from "next-mdx-remote";

import { IoSparkles } from "react-icons/io5";

type Props = {
    message: Message;
};

const ChatMessage = ({ message }: Props) => {
    const { role, content } = message;

    const [mdxData, setMdxData] = useState<MDXRemoteSerializeResult<
        Record<string, unknown>,
        Record<string, unknown>
    > | null>(null);

    const parseContent = useCallback(async () => {
        const mdxContent = await serialize(content, {
            mdxOptions: { development: process.env.NODE_ENV === "development" },
        });

        setMdxData(mdxContent);
    }, [content])

    useEffect(() => {
        parseContent();
    }, [content, parseContent]);

    return (
        <div className="flex">
            {role === "user" ? (
                <Image
                    alt="user"
                    src={
                        "/default_user_ico.jpeg"
                    }
                    height={32}
                    width={32}
                    className="rounded-full shrink-0 size-[32px]"
                />
            ) : (
                <IoSparkles className="shrink-0 text-[#A254FC] size-[32px]" />
            )}
            <div className="flex-1 ml-4">
                <div className="prose space-y-4">
                    {mdxData !== null && (
                        <MDXRemote
                            components={{
                                p: (props: any) => ( <p {...props} className="text-foreground/80 leading-[1.9]" />),
                                a: (props : any) => <a {...props} className="text-foreground font-normal duration-300 ease-in-out decoration-foreground/40 hover:decoration-foreground/80 decoration-1 underline-offset-4"/>,
                                ul : (props : any) => <ul {...props} className="space-y-2 list-disc"/>,
                                li: (props : any) => <li {...props} className='text-foreground/80' />,
                                strong: (props : any) => <strong {...props} className="text-foreground" />,
                                h1: (props : any) => <h1 {...props} className='text-foreground text-lg font-medium' />,
                                h3: (props : any) => <h3 {...props} className='text-foreground text-lg font-medium' />,
                                h4: (props: any) => <h4 {...props} className='font-medium text-foreground text-lg' />,
                            }}
                            scope={{}}
                            frontmatter={{}}
                            compiledSource={mdxData.compiledSource}
                        />
                    )}
                </div>
            </div>
        </div>
    );
};

export default ChatMessage;


```

It does work on development but with an thesame error

![image](https://github.com/user-attachments/assets/9eec441a-2f32-4c39-bc89-aec8763b7ddf)

```
 ✓ Compiled in 1698ms (1616 modules)
 ⨯ Instead change the require of serialize.js in /home/.../.next/server/app/page.js to a dynamic import() which is available in all CommonJS modules.
    at next-mdx-remote/serialize (/home/.../.next/server/app/page.js:110:18)
    at __webpack_require__ (/home/.../.next/server/webpack-runtime.js:33:42)
    at eval (./src/components/ai-chat/chat-message.tsx:10:83)
    at (ssr)/./src/components/ai-chat/chat-message.tsx (/home/.../.next/server/app/page.js:195:1)
    at __webpack_require__ (/home/.../.next/server/webpack-runtime.js:33:42)
    at eval (./src/components/ai-chat/index.tsx:12:71)
    at (ssr)/./src/components/ai-chat/index.tsx (/home/.../.next/server/app/page.js:206:1)
    at Object.__webpack_require__ [as require] (/home/.../.next/server/webpack-runtime.js:33:42)
digest: "3295496001"
 GET / 500 in 488ms
 ✓ Compiled /favicon.ico in 336ms (688 modules)
 GET /favicon.ico 200 in 443ms
```

But will fail on build

```
  ▲ Next.js 14.2.5
  - Environments: .env.local

   Creating an optimized production build ...
 ✓ Compiled successfully

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (4/6)  [==  ]Error [ERR_REQUIRE_ESM]: require() of ES Module /home/.../some-project/node_modules/.pnpm/next-mdx-remote@5.0.0_@types+react@18.3.3_react@18.3.1/node_modules/next-mdx-remote/serialize.js from /home/.../some-project/.next/server/app/page.js not supported.
Instead change the require of serialize.js in /home/.../some-project/.next/server/app/page.js to a dynamic import() which is available in all CommonJS modules.
    at mod.require (/home/.../some-project/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:65:28)
    at 387 (/home/.../some-project/.next/server/app/page.js:9:164820)
    at Object.t [as require] (/home/.../some-project/.next/server/webpack-runtime.js:1:127)
    at require (/home/.../some-project/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18490)
    at I (/home/.../some-project/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94362) {
  code: 'ERR_REQUIRE_ESM',
  digest: '3952180614'
}

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/.../some-project/node_modules/.pnpm/next-mdx-remote@5.0.0_@types+react@18.3.3_react@18.3.1/node_modules/next-mdx-remote/serialize.js from /home/.../some-project/.next/server/app/page.js not supported.
Instead change the require of serialize.js in /home/.../some-project/.next/server/app/page.js to a dynamic import() which is available in all CommonJS modules.
    at mod.require (/home/.../some-project/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:65:28)
    at 387 (/home/.../some-project/.next/server/app/page.js:9:164820)
    at Object.t [as require] (/home/.../some-project/.next/server/webpack-runtime.js:1:127)
    at require (/home/.../some-project/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18490)
    at I (/home/.../some-project/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94362)
 ✓ Generating static pages (6/6)

> Export encountered errors on following paths:
	/page: /
 ELIFECYCLE  Command failed with exit code 1.
```

Do you know library that can be used on client component using nextjs 14? I'll use it as a work around for the mean time.
